# NumPy 创建数组

除了通过底层 ndarray 构造器（即 np.array ）来创建数组，也可通过其他几种方式快速创建：

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like


## numpy.arange

numpy.arange 方法创建一个一维数组：

```python
numpy.arange(length) # 创建一个从0开始长度为length的一维数组
numpy.arange(start, end, step = 1, dtype) # 创建一个从start到end（不包括end），间隔为 step 的数组
```

* dtype 默认类型为输入数据的类型

In [16]:
import numpy as np
x = np.arange(10)
print(x)
y = np.arange(1, 10, 2)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## numpy.linspace

生成等差数列。与 arange 不同之处在于，arange 指定步长，因此对于 float 无法准确得知生成元素的数量；linspace 则指定获得元素的数量：

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

|参数|描述|
|----|----|
|start|序列起始值|
|stop|序列终止值，若 endpoint为 True，则该值包含于数列|
|num|要生成的等步长的样本数量，默认50|
|endpoint|该值为True，数列包含stop值，反之不包含，默认 True|
|retstep|若为 True，生成数组会显示差距，反之不显示|
|dtype|类型|

In [47]:
from numpy import pi
x = np.linspace(0, 2, 9)
print(x)

y = np.linspace(0, 2 * pi, 10)
print(y)

z = np.sin(x)
print(z)

a = np.linspace(1,10,10)
print(a)

# 也可以生成全部一样的数列
b = np.linspace(1,1,10)
print(b)

# 不包含终止值
c = np.linspace(10, 20, 5, endpoint=False)
print(c)

# 包含终止值
d = np.linspace(10,20,5)
print(d)

# 设置显示间距
e = np.linspace(1,10,10,retstep=True)
print(e)
f = np.linspace(1,10,10).reshape([10,1])
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[0.         0.24740396 0.47942554 0.68163876 0.84147098 0.94898462
 0.99749499 0.98398595 0.90929743]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]
[10.  12.5 15.  17.5 20. ]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


## numpy.logspace

numpy.logspace 函数用于创建等比数列。
```python
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```

|参数|描述|
|----|----|
|start|序列的起始值为：base\*\*start |
|stop|序列的终止值为：base\*\*stop。如果 endpoint 为 true，该值包含于数列中 |
|num|要生成的等步长的样本数量，默认50|
|endpoint|默认True|
|base|对数log底数|
|dtype|ndarray的数据类型|

In [53]:
# 从 10 到 100，等比分10个数
a=np.logspace(1.0, 2.0, num = 10)
print(a)

# 将底数设置为2：
b=np.logspace(1.0, 8.0, num = 8, base = 2.0, dtype=int)
print(b)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  2   4   8  16  32  64 128 256]



## numpy.empty

numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且<b>未初始化</b>的数组：

```python
numpy.empty(shape, dtype = float, order = 'C')
```

#### 参数说明：

|参数|描述|
|----|----|
|shape|数组形状|
|dtype|数据类型，可选|
|order|有"C"和"F"两个选项，分别代表“行优先”和“列优先”，在计算机内存中存储元素的顺序|

创建空数组的实例：



In [3]:
import numpy as np
x = np.empty([3,2], dtype=int) # 可见shape值可以为元组或数组，只要是一维就行
print(x) # 尚未初始化，故元素为随机值

[[7012460 7602281]
 [4391004 4456533]
 [6029377 3211382]]


## numpy.zeros

创建指定大小的数组，数组元素以0填充：

```python
numpy.zeros(shape, dtype = float, order = 'C')
```

In [7]:
# 默认浮点数
x = np.zeros(5)
print(x)

# 设置为整数
y = np.zeros((5,), dtype = int)
print(y)

# 自定义类型
z = np.zeros((2,2), dtype = [('x','i4'),('y','i4')])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## numpy.ones

创建指定形状的数组，数组元素以1来填充：
```python
numpy.ones(shape, dtype = None, order = 'C')
```

In [10]:
# 默认为浮点数
x = np.ones(5)
print(x)

# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## numpy.eye

创建对角矩阵
```python
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
```

|参数|说明|
|----|----|
|N:int|输出的行数|
|M:int|输出的列数，默认N|
|k:int|对角线的下标，默认0表示主对角线。负数表示低对角，正数表示高对角|
|dtype|数据类型|
|order|C或F，行优先或列优先|

In [21]:
x = np.eye(3,5,1,int)
print(x)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


## numpy.identity

与 eye 的区别是只能创建方阵。
```python
numpy.identity(n, dtype=None)
```
|参数|说明|
|----|----|
|n：int|表示输出矩阵的行列数|

In [24]:
x = np.identity(7, int)
print(x)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


## numpy.random.random

从属于random模块，创建 \[0.0，1.0) 之间的随机浮点数

```python
numpy.random.random() # 创建一个随机数
numpy.random.random(shape) # 创建随机数组
```

In [7]:
# 获取一个 [0.0,1.0) 随机数
x= np.random.random()
print(x)

# 获取一个元素全为(-1,1)的随机数组
y = np.random.random((2,3))
print(y)

0.13474251973304263
[[0.93598205 0.51567319 0.76946461]
 [0.58779321 0.78807939 0.93130647]]


# 从已有数组创建数组

## numpy.asarray

从已有数组创建新数组。

```python
numpy.asarray(a, dtype=None, order=None)
```

a 可以是列表、列表的元组、元组、元组的元组、元组的列表、多维数组

In [28]:
x = [1, 2, 3]
a = np.asarray(x)
print(a)

y = (1, 2, 3)
b = np.asarray(y)
print(b)

z = [(1, 2, 3), (4, 5)]  # 注：这种元组元素数量不一致的情况已过时，必须指定 dtype=object
c = np.asarray(z)
print(c)

[1 2 3]
[1 2 3]
[(1, 2, 3) (4, 5)]


## numpy.frombuffer

用于实现动态数组。
接受 buffer 参数，以流的形式读入转化成 ndarray 对象。

```python
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
```

注意：buffer 是字符串时，Python3 默认 str 为 Unicode 类型，故要转成 bytestring 在原str前加上b。

* buffer：可以是任意对象，会以流的形式读入。
* count：读取的数据数量，默认为-1，读取所有数据。
* offset：读取的起始位置，默认为0。

In [34]:
# python3.x
s = b'Hello World'
a = np.frombuffer(s, dtype='S1')
print(a)

# python2.x
# s2 = 'Hello World'
# b = np.frombuffer(s2, dtype='S1')
# print(b)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


## numpy.fromiter

从可迭代对象中建立 ndarray 对象，返回一维数组。

```python
numpy.fromiter(itereable, dtype, count = -1)
```

In [35]:
# 使用 range 函数创建列表对象
list=range(5)
it=iter(list)

# 使用迭代器创建 ndarray
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]
