# 切片

ndarray对象可通过“索引”或“切片”来访问和修改。与Python中list切片操作一样。

## slice() 与 冒号分隔切片

ndarray数组可基于 0-n 下标进行索引，切片对象可通过内置 slice 函数，并设置 start，stop，step 参数切割出新数组。

In [4]:
import numpy as np

a = np.arange(10,20)
print(a)
s = slice(2,7,2) # 从索引 2 开始 到索引 7 停止，间隔为2
print(a[s])

[10 11 12 13 14 15 16 17 18 19]
[12 14 16]


也可以使用冒号分隔切片参数 start:stop:step 进行切片操作：

* 只放一个参数 \[2\] 表示返回该索引相对应的单个元素（没有括号）；
* \[2:\] 表示从该索引后所有项都被提取；
* \[2:7\] 表示提取两个索引之间的项（不包含stop）

In [7]:
a = np.arange(10)
b = a[2:7:2]    # 从2到7，间隔2
print(b)

print(a[5])
print(a[2:])
print(a[2:5])

[2 4 6]
5
[2 3 4 5 6 7 8 9]
[2 3 4]


## 在多维数组的切片中，使用“,”区分维度。

In [25]:
a = np.arange(0,12)
a.shape=(3,4)
print(a)
print(a[0:2, 1:3]) # 下标从0开始，不包括end。

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]


## 省略号...选中当前维度的每个元素

切片可以包含省略号...，来<b><font color="#ff0000">使选择元组的长度与数组的维度相同</font></b>。若在行位置使用省略号，则将返回包含行中元素的 ndarray。

挺难理解的是不是？其实就看省略号在哪个维度上，该维度所有元素都被选中。

上一个是一维数组，因此参数是 \[起点:终点:步长\]，而且不包含终点。

这里是多维数组中的二维数组，若将其当做一维数组，则其各元素视作一个对象。

* ...,1 ：则 ... 等于 1，

In [16]:
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[...,1]) # 第2列
print(a[1,...]) # 第2行
print(a[...,1:]) # 第2列以及剩下所有元素

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


# 高级索引

除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。

## 整数数组索引

以下实例获取数组中(0,0)，(1,1)和(2,0)位置处的元素。

In [21]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])  # 3行2列
y = x[[0, 1, 2], [0, 1, 0]]  # 切片以分别取得 第0、1、2行的第0、1、0列。
print(y)

[1 4 5]


获取4x3数组的四个角的元素：

In [22]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('我们的数组是：')
print(x)
print('\n')
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print('四角元素为：')
print(y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


四角元素为：
[[ 0  2]
 [ 9 11]]


切片: 或 ... 与索引数组结合：

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[1:3, 1:3]  # 行为第1到第2行，列为第1到第二列（从0开始）
c = a[1:3, [1, 2]]  # 行为第1到第2行，列为下标1到2（从0开始）
d = a[..., 1:]  # 行为全部，列为第1列到最后（从0开始）
print(b)
print(c)
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 布尔索引
通过一个布尔数组来索引目标数组。

布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

以下获取大于5的元素：

In [26]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('我们的数组是：')
print(x)
# 只打印大于5的元素：
print(x[x > 5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]


取补运算符（就是非） ~ 过滤 NaN：

In [31]:
# 过滤 NaN 元素：
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])  # 配合 np.isnan() 方法

# 过滤非复数元素：
b = np.array([1, 2+6j, 5, 3.5+5j])
print(b[np.iscomplex(b)])

[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]


## 花式索引

指利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标进行取值。

对于使用一维整型数组作为索引，若目标是一维数组，则索引结果是对应下标的行，若目标为二维数组，则对应位置的元素。

与切片不同，<font color="#ff0000"><b>花式索引总是复制数据到新数组中</b></font>。

In [59]:
# 顺序索引数组
x = np.arange(32).reshape((8, 4))  # 8行4列
print(x)
print(x[[4, 2, 1, 7]])  # 分别取 第 4、2、1、7 行
print(x[[4, 2, 1, 7], [1]])  # 取结果的第1列。
# [1]实际是[1,1,1,1]的简写。只能使用1个或4个元素的数组。
print(x[[4, 2, 1, 7][1]])  # 取结果的第1行

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[17  9  5 29]
[ 8  9 10 11]


In [55]:
# 倒序索引数组
x = np.arange(32).reshape((8,4))
print(x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [57]:
# 传入多个索引数组（要使用 np.ix_ 方法）
x = np.arange(32).reshape((8, 4))
print(x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])
print(x[[1, 5, 7, 2], [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[ 4 23 29 10]


### 关于 np.ix_

我尝试了不使用此函数，直接以逗号分隔两个(4,4)数组，则返回的是一个(1,4)矩阵。
因此 np.ix_ 不直接等同于逗号。

np.ix_ 输入了两个列表，第一个列表存放待提取元素的行标（其实就是当做一维对象数组的下标），第二个列表存放的是待提取元素的列标（可以认为是第一次提取后，针对每一个列表元素，再次进行提取并组合）。