# 广播（Broadcast）

是 numpy 对不同形状(shape）的数组进行数值计算的方式。对数组的算术运算通常在相应的元素上进行。

如果两个数组a和b形状相同（`a.shape==b.shape`），那么 `a*b`结果是a与b数组的对应位相乘。这要求维数相同，且各维度的长度相同。



In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


当运算中的两个数组形状不同时，numpy 自动触发广播机制。
<img src='https://www.runoob.com/wp-content/uploads/2018/10/image0020619.gif'>

In [3]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([1,2,3]) # 作为一行元素，向列方向广播
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [5]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## 广播的规则

* 让所有输入数组