### 测试NumPy是否安装成功：

In [1]:
from numpy import *
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# NumPy Ndarray 对象

N维数组对象 ndarray，一系列<b>同类型</b>数据的集合，以 0 为下标开始进行集合中元素的索引。每个元素在内存中有相同存储大小的区域。

内部组成：
* 一个指向数据（内存或内存映射文件中一块数据）的指针。
* 数据类型或dtype，描述在数组中的固定大小值的格子。
* 一个表示数组形状（shape）的元组，表示各维度大小的元组。
* 一个跨度元组（stride），其中的整数是为了前进到当前维度下一个元素需要“跨过”的字节数。

<img src="https://www.runoob.com/wp-content/uploads/2018/10/ndarray.png">

跨度可以是负数，这样使得数组在内存中后向移动，切片中 obj[::-1] 或 obj[:,::-1]。

创建一个 ndarray只需调用 NumPy 的 array函数：

```py
numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
```

|参数|说明|
|:----:|:----|
|object|数组或嵌套的数列|
|dtype|数组元素的数据类型，可选|
|copy|对象是否需要复制，可选|
|order|创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|
|subok|默认返回一个与基类类型一致的数组|
|ndmin|指定生成数组的最小维度|

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 多于一个维度
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
# 最小维度
a = np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [4]:
# dtype参数
a = np.array([1,2,3], dtype=complex)
print(a) # 为什么不是i而是j？因为是按照电气工程师约定：i表示电流，j表示-1的平方根

[1.+0.j 2.+0.j 3.+0.j]
