# NumPy数组的基本属性

数组的维度称为“秩（rank）”，秩就是轴的数量，即数组的维度，一位数组的秩为1，二维数组为2，以此类推。

每一个线性的数组称为一个“轴（axis）”，也就是维度（dimensions）。例如，二维数组相当于两个一维数组，其中第一个一位数组中的每一个元素又是一个一维数组。

因此一维数组就是Numpy中的轴（axis）。第一个轴相当于底层数组，第二个轴是底层数组里的数组。

对于二维数组（矩阵），可以声明 axis=0，表示沿着第0轴进行操作，即对每一列进行操作。axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

（？？？）无法理解。

NumPy 数组中重要的 ndarray 对象属性：

|属性|说明|
|:----:|:----|
|ndrray.ndim|秩，即轴的数量或维度|
|ndarray.shape|数组的维度，对于矩阵，n行m列|
|ndarray.size|数组元素的总数，闲相当与 .shape 中的 `n*m` 的值|
|ndarray.dtype|元素类型|
|ndarray.itemsize|每个元素的大小，以字节为单位|
|ndarray,flags|ndarray对象的内存信息|
|ndarray.real|元素的实部|
|ndarray.imag|元素的虚部|
|ndarray.data|包含实际数组元素的缓冲区，由于一般使用数组索引获取元素，故通常不用|

## ndarray.ndim

用于返回数组的维度（秩）

In [11]:
import numpy as np

a = np.arange(24)
print(a.ndim) # a此时只有一个维度
print(a)
b = a.reshape(2,4,3) # b此时有三个维度。注：reshape通常返回非拷贝副本
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


## ndarray.shape

ndarray.shape 表示数组的维度，返回一个元组，该元组长度就是维度的数目，如一个二维数组，其维度表示“行数”和“列数”。

ndarray.shape 也可用于调整数组大小。

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [8]:
# 调整数组大小
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# 或者使用 reshape方法 调整数组大小
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


可以看出，shape和reshape()是将元素当做一维数组，重新切分。

## ndarray.itemsize

以<b>字节</b>的形式返回数组中每一个元素的大小。

例如，一个元素类型为 float64 的数组，itemsize 属性值为8。
又如，一个元素类型为 complex32 的数组 itemsize 属性为 4。

In [12]:
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

y= np.array([1,2,3,4,5], dtype = np.float64)
print(y.itemsize)

1
8


## ndarray.flags

ndarray.flags 返回 ndarray 对象的内存信息，包含以下属性：

|属性|描述|
|:----:|:----|
|C_CONTIGUOUS(C)|数据在一个单一的C分格连续段中|
|F_CONTIGUOUS(F)|数据在一个单一的Fortran分格的连续段中|
|OWNDATA(O)|数组拥有它所使用的内存，或从另一个对象中借用它|
|WRITEABLE(W)|数组区域可以被写入，将该值设置为False，则数据为只读|
|ALIGNED(A)|数据和所有元素都适当地对齐到硬件上|
|UPDATEIFCOPY(U)|这个数组是其它数组的一个副本，当这个数组被释放，原数组内容将被更新|

In [13]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

